retrosheet_analytics:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: password1
      dbname: retrosheet
      schema: mart
  target: dev