version: 2

sources:
  - name: stage
    tables:
      - name: game_logs
      - name: park_code
      - name: people
      - name: teams

models:
  - name: dim_park
    columns:
      - name: park_key
        tests:
          - not_null
          - unique
  - name: dim_person
    columns:
      - name: person_id
        tests:
          - not_null
          - unique
      - name: is_player
        tests:
          - not_null
      - name: is_mgr
        tests:
          - not_null
      - name: is_coach
        tests:
          - not_null
      - name: is_ump
        tests:
          - not_null
  - name: dim_team
    columns:
      - name: team_key
        tests:
          - not_null
          - unique
      - name: team_abbr
        tests:
          - not_null
      - name: league
        tests:
          - not_null
