version: 2

models:
  - name: agg_team_stats
    columns:
      - name: team_key
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('dim_team')
              field: team_key